server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 5
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**
            - id: inventory-service-route
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/inventory/**
  data:
    redis:
      host: noted-maggot-150363.upstash.io
      port: 6379
      password: gQAAAAAAAktbAAIgcDI4MzMyYzdhNzVjYjQ0YjE1YjNkOTNlNDhiN2RjMWE4ZA
      ssl:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: unrestricted
